name: Build and Publish Modal Image to Docker Hub

on:
    push:
        branches:
            - main
        paths-ignore:
            - ".github/**"
            - "README.md"
    workflow_dispatch:

env:
    IMAGE_NAME: mirumoji-modal-gpu
    REGISTRY: docker.io

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Clean Up Cache
              run: |
                  docker system prune -af || true
                  sudo rm -rf /usr/share/dotnet || true
                  sudo rm -rf /usr/local/lib/android || true
                  sudo rm -rf /opt/ghc || true
                  sudo rm -rf /tmp/* || true
                  sudo apt-get clean

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./modal_processing/Dockerfile.modal
                  push: true
                  platforms: linux/amd64
                  tags: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
                  # Add estargz compression so Modal pulls faster
                  outputs: |
                      type=registry,compression=estargz,oci-mediatype=true,force-compression=true
