# .github/workflows/licenses-backend.yml
name: Backend licenses & SBOM

on:
  workflow_dispatch:

jobs:
  backend-licenses:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # 2) Install deps + generate NOTICE.md
    - name: Build NOTICE
      run: |
        python -m pip install -U pip-licenses==5.*
        python -m pip install -r mirumoji_open_api/requirements.txt
        pip-licenses \
          --with-authors \
          --with-license-file \
          --format=markdown \
          --output-file NOTICE-backend.md

    - name: Build SBOM
      uses: anchore/sbom-action@v0
      with:
        format: spdx-json
        upload-artifact: true         # SBOM
        dependency-snapshot: false

    # 4) Upload NOTICE.md
    - name: Upload NOTICE artefact
      uses: actions/upload-artifact@v4
      with:
        name: NOTICE-backend
        path: NOTICE-backend.md
