name: License & SBOM (backend)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # for SBOM submission
  security-events:  write # to fix GH dependency graph

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: {submodules: recursive}

    # ---------- 1.  Inventory + notice file  ----------
    - name: Install deps
      run: |
        python -m pip install -U pip-licenses==5.*
        python -m pip install -r requirements.txt
    - name: Generate NOTICE
      run: |
        pip-licenses \
          --with-authors \
          --with-license-file \
          --format=md \
          --output-file ../licenses/NOTICE-backend.txt

    # ---------- 2.  Create SBOM & push to GH dependency graph ----------
    - name: Build SPDX SBOM and submit
      uses: anchore/sbom-action@v0
      with:
        format: spdx-json
        upload-artifact: true          # keeps a copy under “Actions ▸ artifacts”
        dependency-snapshot: true      # fixes GH’s dependency graph
